### ISSUE TITLE
should support new octal prefix 0o

### ISSUE THREAD

**Issue by hax** [d3x0r/JSON6#11]
As title.

And I suggest do not allow `0` prefix because ES6+ and ES5 strict mode do not allow it any more.

**Comment by d3x0r** [comment]
It does.
Although 0 prefix is apparently broken.  This is a documentation issue....

**Comment by d3x0r** [comment]
For the javascript version I really just take the collected characters of a number and feed it through Number(val.string).  So whatever javascript does is what this does; other than if a leading 0 I stuff a 'o' now... which I'm debating about before publishing.
