### ISSUE TITLE
JSON5 superset?

### ISSUE THREAD

**Issue by brettz9** [d3x0r/JSON6#18]
Is JSON6 a strict superset of JSON5? I'd just like to make it easier for users if they are already familiar with JSON5. In the README, it looks like it should be, but I wanted to be sure.

**Comment by d3x0r** [comment]
I'm pretty sure it includes everything JSON5 did before.

**Comment by mathiasrw** [comment]
It would be good to state very clearly in the readme - so that you know that you can read your json5 documents with json6

**Comment by d3x0r** [comment]
@mathiasrw  https://github.com/d3x0r/JSON6/blob/master/README.md#summary-of-changes-from-json5 ?

**Comment by brettz9** [comment]
LGTM, thanks!
