### ISSUE TITLE
Stringify support

### ISSUE THREAD

**Issue by keith0305** [d3x0r/JSON6#21]
Hey,

Very cool library and I appreciate the hard work, but one thing that kept me from using this in a large project is the missing Stringify feature.

Are you planning to add it eventually or that is not in your plan at all?
If no, why? :(

If yes, what are the difficulties? Do you need help?
I am no expert especially on the low-level stuff like parsing, but today I will clone the repo and dive into the source code a bit.

**Comment by d3x0r** [comment]
Somewhat; there's not a lot of benefit from a stringifier for this.  I did add one in https://github.com/d3x0r/jsox which is very similar code to this.

What things would you expect this to do better than JSON.stringify() ?

**Comment by keith0305** [comment]
I am working on a custom CMS system where I am using nodejs to generate a JSON that will might eventually be edited by hand by developers or admin. This is where I need those JSON file to be stored in "JSON6" format so that it would be easier to read and edit by a human.

I am considering JSON5 library but JSON6's speed is unmatched (on top of other features like backtick strings).

**Comment by d3x0r** [comment]
Oh okay.
I will look into adding that.  it's been on my backlist a while :)

**Comment by keith0305** [comment]
Cool! Appreciate your hard work man.

**Comment by d3x0r** [comment]
I published 1.1.1 on npm (up from 1.0.8), it includes a custom stringifier that emits NaN and Infinity, and unquoted field names (unless the need a quote).

**Comment by keith0305** [comment]
Omg thank you ♥
