### ISSUE TITLE
update to def-dependecies is absolutly needed

### ISSUE THREAD

**Issue by KilianKilmister** [d3x0r/JSON6#22]
**JSON6** looked attractive for a project of mine, but lacks a **VS-Code** language extention.
so i wanted to whip one up quickly and for that i wanted to look at your code.
If you can fix the dev-dependencies I will make you a **Vs-Code** extention for **JSON6**

exept for ```acorn```and ```regenerate``` everything is dangerously outdated
i would have fixed it myself but i never used mocha so i dont know how to adjust the tests.
### special mentions:
|dep|version|issue|note|
|---|---|---|---|
|core-js|2.6.5|deprecated|update|
|rollup-plugin-node-resolver|3.4.0|deprecated|use @rollup/plugin-node-resolve|
|rollup-plugin-bubble|0.19.6|deprecated|use @rollup/plugin-buble|
|rollup-plugin-commonjs|9.2.1|deprecated|use @rollup/plugin-commonjs|
|mocha|3.1.0|security issues: command injection and DOS|update!|np
___
I would also advise to ditch the eslint-plugin-mess and just use **standard/standard **
it's uses eslint anyways and you are useing the plugin for it allready, just makes it a little easier  
[![JavaScript Style Guide](https://img.shields.io/badge/code_style-standard-brightgreen.svg)](https://standardjs.com)

**Comment by d3x0r** [comment]
(dev-dependancies? )
Okay; I should actually clean out most of those, this doesn't need a lot of packaging; and the test framework was never really implemented.
Thanks for the notice, I will look.

**Comment by d3x0r** [comment]
https://github.com/d3x0r/JSON6/tree/1.0.5 includes changes to rollup.config.js and dev dependancies.  

Publishd 1.0.5 to npm.

**Comment by KilianKilmister** [comment]
Cool, just pulled it and looking what i can come up with
