### ISSUE TITLE
License link in readme is broken.

### ISSUE THREAD

**Issue by jdalton** [d3x0r/JSON6#3]
The link in the readme:
> ## License
>
>MIT. See [LICENSE.md](./LICENSE.md) for details.

Is broken

It looks like maybe JSON6 started as JSON5 and then changed, based on readme changes at least. If so you'll want to include the copyright note of JSON5 in the JSON6 license similar to how I do it with [Lodash](https://github.com/lodash/lodash/blob/master/LICENSE).

Or if it JSON6 was derived from [d3x0r/SACK/src/netlib/html5.websocket/json/json6_parser.c](https://github.com/d3x0r/SACK/blob/master/src/netlib/html5.websocket/json/json6_parser.c) then you'll want to include [SACK](https://github.com/d3x0r/SACK)'s copyright notice *(what is SACK licensed as?)*.

**Comment by jdalton** [comment]
It looks like JSON6 started as JSON5 and then gradually changed (based on readme changes at least). You'll want to include the copyright note of JSON5 in the JSON6 license then... similar to how I do it with [Lodash](https://github.com/lodash/lodash/blob/master/LICENSE).

**Comment by d3x0r** [comment]
SACK is a LGPL.  (separating it from above layers of usage.  It's meant to be linked to dynamically; otherwise if linked statically I could technically reverse engineer the user's app to fix/change SACK code.)

Added MIT lisense to Lisense.md..

**Comment by jdalton** [comment]
Thank you @d3x0r!
