### ISSUE TITLE
Remove old-style octal string escape support

### ISSUE THREAD

**Issue by brettz9** [d3x0r/JSON6#35]
Figured there should be an open issue to track the possible removal of old-style octal string supports, consistent with removal of octal numbers and as consistent with strict mode and ES6 Modules (which have implicit strict mode), as being discussed in #29 (since that was merged).

**Comment by d3x0r** [comment]
blame this commit.
https://github.com/d3x0r/JSON6/commit/bbd4786f88eb5064acd7995c965a5e6a33945a85

**Comment by brettz9** [comment]
So it looks like this can be closed now, so closing. Thanks!
