### ISSUE TITLE
string_status is undefined

### ISSUE THREAD

**Issue by jdalton** [d3x0r/JSON6#4]
When using JSON6 I get an error `string_status` is `undefined`. I'm bundling JSON6 into a project that uses strict mode `"use strict"`.

If you add `"use strict"` to the top of [lib/json6.js](https://github.com/d3x0r/JSON6/blob/c1b2aed251a10e9d80c8c67abc5e30ad43a9e791/lib/json6.js) it would catch the undefined variable assignment to `string_status`.

**Comment by jdalton** [comment]
If you add `"use strict"` to the top of https://github.com/d3x0r/JSON6/blob/c1b2aed251a10e9d80c8c67abc5e30ad43a9e791/lib/json6.js it would catch the undefined variable assignment to `string_status`.

**Comment by jdalton** [comment]
Same with var `exponent_digit`.

**Comment by d3x0r** [comment]
Fixed, published and pushed.  Added "use strict" in json6.js anyway.  Cleaned up some bad ugly throws, and -Infinity handling.

**Comment by jdalton** [comment]
🤘 Thank you @d3x0r!
