### ISSUE TITLE
parse should coerce value to a string if it isn't.

### ISSUE THREAD

**Issue by jdalton** [d3x0r/JSON6#5]
Hi @d3x0r!

Thank you for JSON6 :yum:!
I tried to pass a file buffer to `JSON6.parse` and it didn't coerce to a string like with `JSON.parse`.

**Comment by d3x0r** [comment]
https://stackoverflow.com/questions/41951307/convert-a-json-object-to-buffer-and-buffer-to-json-object-back

`var temp = JSON.parse(buf.toString());`


What sort of buffer?
Do you have an example code?

**Comment by jdalton** [comment]
It's a buffer from `fs.readFileSync(filePath)`. I could pass an encoding `"utf8"` but expected parse to coerce. The easiest way for you to support it is to add the following check
```js
if (typeof msg !== "string") {
  msg = String(msg)
}
```
This should tackle it and avoid issue with things like symbols too.

**Comment by jdalton** [comment]
The `String()` constructor avoids issues with symbols that `msg + ""` would have.

**Comment by d3x0r** [comment]
Okay updated, pushed and published.

**Comment by jdalton** [comment]
Thank you, that fixed it!
