### ISSUE TITLE
require a broken JSON6 does not throw an error

### ISSUE THREAD

**Issue by BananaAcid** [d3x0r/JSON6#51]
Is that wanted behaviour?

Version 1.1.1

test string required and parsed:
```
{
```

throws no error.

Testet with `JSON6.parse('{');`

... it seems, there is no error, if an object is not closed.

---

2nd;

Getting it to trigger error with require, there is no filename included.
```
"fault while parsing; character unexpected 'v' unexpected at 342 (near '   [v]ersion: "0') [2:6]"
```

If a module fails with require, it mentions what file it is.

**Comment by d3x0r** [comment]
:) interesting.  I will add a test case for this and fix it; I need a few hours...

**Comment by d3x0r** [comment]
Added test which passed without any additional modifications; updated version and published 1.1.2.  Please let me know if there's additional issues.  (I'm not sure about the reporting of which file failed.)

**Comment by BananaAcid** [comment]
Hm? That means, that is expected behavior?

**Comment by d3x0r** [comment]
that means it was fixed already in the meantime, and really just requires publishing...
