### ISSUE TITLE
write a json6 to json online converter

### ISSUE THREAD

**Issue by Kreijstal** [d3x0r/JSON6#54]
like a real bro

**Comment by d3x0r** [comment]
ok.

**Comment by d3x0r** [comment]
https://d3x0r.github.io/json_json6_jsox_converter/  Something like this?

JSON6 doesn't really have a lot to output for its own.... it didn't add date or bignum support... best it could do is occasionally write object fields without quotes....

[JSOX](https://github.com/d3x0r/jsox) is better than JSON6 in lots of ways...

**Comment by Kreijstal** [comment]
bretty good
