### ISSUE TITLE
JSON6 vs JSON-6

### ISSUE THREAD

**Issue by croqaz** [d3x0r/JSON6#7]
Hi,

There are 2 JSON6 packages on NPM:

* https://www.npmjs.com/package/json6
* https://www.npmjs.com/package/json-6

The latter seems to be the correct one, but the documentation is wrong.
I can create a PR and fix it, if you want.

**Comment by jdalton** [comment]
@croqaz A PR would be great!

**Comment by d3x0r** [comment]
got it :)  yes npm install json-6 should be what it is.... I did some updates before finding it was already taken.

Working on another issue ATM but I have it included in next push/publish.

**Comment by d3x0r** [comment]
Docs updated...
