### ISSUE TITLE
Weird Arrays

### ISSUE THREAD

**Issue by croqaz** [d3x0r/JSON6#8]
Hi again,

I found a weird bug when parsing Arrays.

```js
var JSON6 = require('json-6')
var d = '[ {a: "", b: ""}, {a: "", b: ""} ]'
var r = JSON6.parse(d)
// [ { a: '', b: '' }, <1 empty item>, { a: '', b: '' } ] //  <empty item> ???
Array.isArray(r)
// true
```

**Comment by d3x0r** [comment]
Yup; I see.  Working on it.

**Comment by d3x0r** [comment]
Should be fixed [test](./tests/json6TestObjectArray.js)

**Comment by croqaz** [comment]
That solves it! Fantastic!

**Comment by d3x0r** [comment]
Was testing performance and found that 'let' can cause deoptimizations.  FIxed to restore performance over json5.
